### ISSUE TITLE
[Travis] HAPI2プラグインのテストがストールする

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1309]
Travis上でHAPI2プラグインのテストがストールするようになった。
ローカル(Ubuntu 14.04)では再現していない。

masterで出始めたのはこれか

https://travis-ci.org/project-hatohol/hatohol/builds/67779459

その直前は以下

https://travis-ci.org/project-hatohol/hatohol/builds/67777226

**Comment by ashie** [comment]
永遠に止まる可能性があるのはこの辺か

https://github.com/project-hatohol/hatohol/pull/1272/files#diff-c6d4fc34a6a3fbddd859bda41cbddc62R104

**Comment by Mnakagawa** [comment]
CommadQueueだったり，multiprocessing.Queueの可能性は大きいですね。
提示して頂いている例もCommandQueueですし

**Comment by ashie** [comment]
無限ループになる可能性を止めてみたら突破した

https://travis-ci.org/ashie/hatohol/builds/68442306

今までもまれに突破することもああったので、一回だけじゃ偶然かもしれないので、
もう一回試してみる

**Comment by ashie** [comment]
2回目:

https://travis-ci.org/ashie/hatohol/jobs/68442308

ストールした。

**Comment by ashie** [comment]
メモ

```
$ server/hap2/test/run-test.sh -v
```

で詳細出力が得られる

**Comment by ashie** [comment]
メモ

**Comment by ashie** [comment]
test_pop_allなのは合っているようだ。

```
test_pop_all (TestHaplib.CommandQueue) ... 

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by ashie** [comment]
CommandQueueのpop_allで、__q.empty()はFalseなのに__q.get()をするとQueue.Emptyが
返ってくるというのを延々繰り返しているようだ。

**Comment by kz0817** [comment]
まじで！バッグラウドスレッドがなんらかの事情で実行されずいつまでも、Qからデータがとれないのか？

**Comment by ashie** [comment]
Queue.get()のtimeoutをNoneにすると成功しているみたい（別のテストで失敗している）。

https://travis-ci.org/ashie/hatohol/jobs/69083542

この文脈でNoneにするのが正しいのかどうかはよくわかっていないのですが、以下をみるとtimeoutが
0以下の場合のどういう動作になるのかよく分からない。

https://docs.python.org/2/library/queue.html#Queue.Queue.get

**Comment by ashie** [comment]
> 0以下の場合のどういう動作になるのかよく分からない。

`If optional args block is true` や `Otherwise` がどこからどこまでを指しているのかが曖昧。

**Comment by ashie** [comment]
> この文脈でNoneにするのが正しいのかどうかはよくわかっていないのですが、以下をみるとtimeoutが
> 0以下の場合のどういう動作になるのかよく分からない。

`block=True` で `timeout=0` するくらいなら `block=false` にすべきだと思うので、やっぱり意図としては
None でいいのかな。

それはpull requestを出すとして、そこを突破しても今度は以下のような失敗をするようになった

```
======================================================================

ERROR: test_reply (TestRabbitMQConnector.TestRabbitMQConnector)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/ashie/hatohol/server/hap2/test/TestRabbitMQConnector.py", line 56, in test_reply

    conn = self.__create_connected_connector()

  File "/home/travis/build/ashie/hatohol/server/hap2/test/TestRabbitMQConnector.py", line 88, in __create_connected_connector

    conn.setup(self.__get_default_transporter_args())

  File "/home/travis/build/ashie/hatohol/server/hap2/rabbitmqconnector.py", line 63, in setup

    connection = pika.adapters.blocking_connection.BlockingConnection(param)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 32, in __init__

    BaseConnection.__init__(self, parameters, None, reconnection_strategy)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 50, in __init__

    reconnection_strategy)

  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 170, in __init__

    self._connect()

  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 228, in _connect

    self.parameters.port or  spec.PORT)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 44, in _adapter_connect

    self._handle_read()

  File "/usr/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 151, in _handle_read

    data = self.socket.recv(self._suggested_buffer_size)

timeout: timed out

======================================================================

ERROR: test_run_receive_loop (TestRabbitMQConnector.TestRabbitMQConnector)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/ashie/hatohol/server/hap2/test/TestRabbitMQConnector.py", line 73, in test_run_receive_loop

    conn.setup(self.__get_default_transporter_args())

  File "/home/travis/build/ashie/hatohol/server/hap2/rabbitmqconnector.py", line 63, in setup

    connection = pika.adapters.blocking_connection.BlockingConnection(param)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 32, in __init__

    BaseConnection.__init__(self, parameters, None, reconnection_strategy)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 50, in __init__

    reconnection_strategy)

  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 170, in __init__

    self._connect()

  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 228, in _connect

    self.parameters.port or  spec.PORT)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 44, in _adapter_connect

    self._handle_read()

  File "/usr/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 151, in _handle_read

    data = self.socket.recv(self._suggested_buffer_size)

timeout: timed out

======================================================================

ERROR: test_setup (TestRabbitMQConnector.TestRabbitMQConnector)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/ashie/hatohol/server/hap2/test/TestRabbitMQConnector.py", line 44, in test_setup

    conn.setup(self.__get_default_transporter_args())

  File "/home/travis/build/ashie/hatohol/server/hap2/rabbitmqconnector.py", line 63, in setup

    connection = pika.adapters.blocking_connection.BlockingConnection(param)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 32, in __init__

    BaseConnection.__init__(self, parameters, None, reconnection_strategy)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 50, in __init__

    reconnection_strategy)

  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 170, in __init__

    self._connect()

  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 228, in _connect

    self.parameters.port or  spec.PORT)

  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 44, in _adapter_connect

    self._handle_read()

  File "/usr/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 151, in _handle_read

    data = self.socket.recv(self._suggested_buffer_size)

timeout: timed out

----------------------------------------------------------------------
```

**Comment by ashie** [comment]
> If optional args block is true や Otherwise がどこからどこまでを指しているのかが曖昧。

以下をみたら、Otherwiseはblock=Falseのことだと書いてあった

https://docs.python.org/2.7/library/queue.html#Queue.Queue.get

**Comment by ashie** [comment]
> それはpull requestを出すとして、そこを突破しても今度は以下のような失敗をするようになった

`retry_delay`と`socket_timeout`を試そうとしたが、Travisではどっちもセットできない。

```
TypeError: __init__() got an unexpected keyword argument 'socket_timeout'
```

手元ではどっちも使える。

**Comment by ashie** [comment]
pikaを更新したらtimeoutは突破したようだが、次はこれ

> ProbableAuthenticationError

RabbitMQのユーザーが設定されていないのかな？

**Comment by ashie** [comment]
> RabbitMQのユーザーが設定されていないのかな？

これは調査ブランチの問題だった
加速するためにいろいろ殺していたが、必要なものまで殺していた

**Comment by ashie** [comment]
というわけで、HAP2のテストは以下のPRですべて解決していた。

https://github.com/project-hatohol/hatohol/pull/1339

**Comment by kz0817** [comment]
:kissing_heart:
