### ISSUE TITLE
[15.06] [HAPI2.0] [Server] Invalid time stamp formatとログに出力され続ける

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1376]
一度HAPI2.0のプラグインと接続し，その後監視サーバーからそのプラグインの情報を削除したにも関わらず，
以下のようにログに30秒毎に出力され続ける。
```
Jul  6 20:50:22 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150629024537.64
Jul  6 20:50:22 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150706115022.535474
Jul  6 20:50:52 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150629024537.64
Jul  6 20:50:52 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150706115052.945759
Jul  6 20:51:23 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150629024537.64
Jul  6 20:51:23 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150706115123.522522
Jul  6 20:51:53 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150629024537.64
Jul  6 20:51:53 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150706115153.920799
Jul  6 20:52:24 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150629024537.64
Jul  6 20:52:24 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150706115224.353829
Jul  6 20:52:54 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150629024537.64
Jul  6 20:52:54 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150706115254.741846
Jul  6 20:53:25 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150629024537.64
Jul  6 20:53:25 localhost hatohol[2505]: [ERR] <HatoholArmPluginGateHAPI2.cc:541> Invalid timestamp format: 20150706115325.184736
```

**Comment by Mnakagawa** [comment]
詳細：
監視サーバー情報は削除したが，プラグインは起動したまま。
ポーリング間隔毎にRabbitMQのキューにメッセージを送り続けていた。
監視サーバーの情報を削除しても，一度つながったキューとの接続は切れないということ？

**Comment by Mnakagawa** [comment]
またそうであるならば，ログはプラグイン側からのタイムスタンプが間違っていることを表している。
ぱっとみ何か問題があるようには見えないがHatoholArmPluginGateHAPI2内の
parseTimeStampのどこかのフィルタに引っかかってERRセクションに飛んでいる。

**Comment by ashie** [comment]
> またそうであるならば，ログはプラグイン側からのタイムスタンプが間違っていることを表している。
> ぱっとみ何か問題があるようには見えないがHatoholArmPluginGateHAPI2内の
> parseTimeStampのどこかのフィルタに引っかかってERRセクションに飛んでいる。

ここからコピペして単体テストに通しても失敗しない。
何かゴミが混じってるようにも見えないが...

**Comment by ashie** [comment]
> 監視サーバーの情報を削除しても，一度つながったキューとの接続は切れないということ？

手元で試している範囲では、ちゃんと止まっているようだ。
うーん...何だろ。

**Comment by Mnakagawa** [comment]
30秒ごとのタイムスタンプは恐らくupdateArmInfo,接続時に大量に同様のメッセージがあったが，
恐らくこれはトリガーやイベントのタイムスタンプと思われる。
それに付随してなのかはわからないが，HAPI2のzabbixではトリガーの情報を取得できない。
タイムスタンプが弾かれるとトリガーは切り捨てられる？サーバー側のソースをまだ読み切れていない。

だがupdateArmInfoの情報はタイムスタンプが弾かれても更新され続けている。
時刻と通信成功回数。

**Comment by Mnakagawa** [comment]
また，トリガーの情報が取得できない，というのはデータベースにデータが入っていないということです。

**Comment by Mnakagawa** [comment]
> 手元で試している範囲では、ちゃんと止まっているようだ。

止まらない…
監視サーバー情報を削除したにも関わらず，RabbitMQとのコネクションが続いている。
また，コネクションが続いていることによりメッセージを受信し続けている。

**Comment by Mnakagawa** [comment]
コネクションが続いていることはRabbitMQのWebUI上から確認

**Comment by Mnakagawa** [comment]
試しにhatoholサーバーを再起動するとトリガーは無事取得できるようになっていた。
しかしタイムスタンプが怒られている点は変わらず。

**Comment by ashie** [comment]
> ここからコピペして単体テストに通しても失敗しない。

CentOSでは失敗する。

**Comment by Mnakagawa** [comment]
どういうことなんだってばよ…

**Comment by ashie** [comment]
これが何とも再現できない。

**Comment by Mnakagawa** [comment]
CentOSでも再現できないということですか？

**Comment by ashie** [comment]
少なくとも現在のmasterでは、CentOSでも再現しないです。

**Comment by Mnakagawa** [comment]
修正を確認。
ヒストリーの取得もやはりこの問題から来てたっぽく，問題なく取得できていた。

**Comment by ashie** [comment]
自分の手元で発生するようになった(Ubuntu)。

amqp_queue_declare ()で刺さっている

```
(gdb) thread apply all bt

Thread 6 (Thread 0xb6140b40 (LWP 21775)):
#0  0xb77c6424 in __kernel_vsyscall ()
#1  0xb729fc8b in poll () at ../sysdeps/unix/syscall-template.S:81
#2  0xb76d920b in g_poll () from /lib/i386-linux-gnu/libglib-2.0.so.0
#3  0xb76ca3e8 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#4  0xb76ca76b in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
#5  0xb701836a in ?? () from /usr/lib/i386-linux-gnu/libgio-2.0.so.0
#6  0xb76f09aa in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#7  0xb766cf70 in start_thread (arg=0xb6140b40) at pthread_create.c:312
#8  0xb72aebee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

Thread 5 (Thread 0xb57ffb40 (LWP 21777)):
#0  0xb77c6424 in __kernel_vsyscall ()
#1  0xb7673135 in sem_wait@@GLIBC_2.1 () at ../nptl/sysdeps/unix/sysv/linux/i386/i686/../i486/sem_wait.S:79
#2  0xb7563f20 in waitWaitChildSem (this=0x9006930) at ChildProcessManager.cc:110
#3  ChildProcessManager::mainThread (this=0x9006638, arg=0x9006740) at ChildProcessManager.cc:336
#4  0xb74965c4 in HatoholThreadBase::threadStarter (data=0x9006740) at HatoholThreadBase.cc:234
#5  0xb76f09aa in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#6  0xb766cf70 in start_thread (arg=0xb57ffb40) at pthread_create.c:312
#7  0xb72aebee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

Thread 4 (Thread 0xb4dffb40 (LWP 21778)):
#0  0xb77c6424 in __kernel_vsyscall ()
#1  0xb7673135 in sem_wait@@GLIBC_2.1 () at ../nptl/sysdeps/unix/sysv/linux/i386/i686/../i486/sem_wait.S:79
#2  0xb7795b72 in mlpl::SimpleSemaphore::wait (this=0xb4407d88) at SimpleSemaphore.cc:93
#3  0xb74961b2 in HatoholThreadBase::waitExit (this=this@entry=0xb4407d58) at HatoholThreadBase.cc:133
#4  0xb74961f7 in HatoholThreadBase::~HatoholThreadBase (this=0xb4407d58, __in_chrg=<optimized out>)
    at HatoholThreadBase.cc:107
#5  0xb75ca637 in ~Worker (this=0xb4407d58, __in_chrg=<optimized out>) at FaceRest.cc:200
#6  FaceRest::Worker::~Worker (this=0xb4407d58, __in_chrg=<optimized out>) at FaceRest.cc:201
#7  0xb75c564f in FaceRest::stopWorkers (this=0xbfc1d0e8) at FaceRest.cc:366
---Type <return> to continue, or q <return> to quit---
#8  0xb75c5cac in FaceRest::mainThread (this=0xbfc1d0e8, arg=0x9000870) at FaceRest.cc:413
#9  0xb74965c4 in HatoholThreadBase::threadStarter (data=0x9000870) at HatoholThreadBase.cc:234
#10 0xb76f09aa in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#11 0xb766cf70 in start_thread (arg=0xb4dffb40) at pthread_create.c:312
#12 0xb72aebee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

Thread 3 (Thread 0xb39ffb40 (LWP 21780)):
#0  0xb77c6424 in __kernel_vsyscall ()
#1  0xb7673135 in sem_wait@@GLIBC_2.1 () at ../nptl/sysdeps/unix/sysv/linux/i386/i686/../i486/sem_wait.S:79
#2  0xb7795b72 in mlpl::SimpleSemaphore::wait (this=0x90066d8) at SimpleSemaphore.cc:93
#3  0xb74961b2 in HatoholThreadBase::waitExit (this=0x9006860) at HatoholThreadBase.cc:133
#4  0xb74964dc in HatoholThreadBase::exitSync (this=0x9006860) at HatoholThreadBase.cc:164
#5  0xb74cf67a in stop (this=0x9024418) at HatoholArmPluginInterfaceHAPI2.cc:391
#6  HatoholArmPluginInterfaceHAPI2::stop (this=this@entry=0x901f6a0) at HatoholArmPluginInterfaceHAPI2.cc:490
#7  0xb761ecff in HatoholArmPluginGateHAPI2::stop (this=this@entry=0x901f698) at HatoholArmPluginGateHAPI2.cc:617
#8  0xb761ef32 in HatoholArmPluginGateHAPI2::~HatoholArmPluginGateHAPI2 (this=0x901f698, __in_chrg=<optimized out>)
    at HatoholArmPluginGateHAPI2.cc:831
#9  0xb761f54c in HatoholArmPluginGateHAPI2::~HatoholArmPluginGateHAPI2 (this=0x901f698, __in_chrg=<optimized out>)
    at HatoholArmPluginGateHAPI2.cc:832
#10 0xb74b3cda in UsedCountable::unref (this=this@entry=0x901f698) at UsedCountable.cc:35
#11 0xb75c1e59 in DataStoreManager::remove (this=this@entry=0x900324c, storeId=2) at DataStoreManager.cc:125
#12 0xb7610a06 in stopDataStore (isRunning=0x0, serverId=@0xb39ff0c0: 2, this=0x9003218) at UnifiedDataStore.cc:182
#13 UnifiedDataStore::deleteTargetServer (this=this@entry=0x9002678, serverId=@0xb39ff0c0: 2, privilege=...)
    at UnifiedDataStore.cc:807
#14 0xb75fce30 in RestResourceServer::handlerDeleteServer (this=this@entry=0xb44086c0) at RestResourceServer.cc:668
#15 0xb7603950 in RestResourceServer::handlerServer (this=0xb44086c0) at RestResourceServer.cc:210
#16 0xb75fcb30 in RestResourceServer::handle (this=0xb44086c0) at RestResourceServer.cc:63
#17 0xb75c4a1f in FaceRest::ResourceHandler::handleInTryBlock (this=this@entry=0xb44086c0) at FaceRest.cc:658
#18 0xb75ca80c in FaceRest::Worker::mainThread (this=0xb4407d58, arg=0xb4407e18) at FaceRest.cc:216
#19 0xb74965c4 in HatoholThreadBase::threadStarter (data=0xb4407e18) at HatoholThreadBase.cc:234
#20 0xb76f09aa in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#21 0xb766cf70 in start_thread (arg=0xb39ffb40) at pthread_create.c:312
---Type <return> to continue, or q <return> to quit---
#22 0xb72aebee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

Thread 2 (Thread 0xb13ffb40 (LWP 21784)):
#0  0xb77c6424 in __kernel_vsyscall ()
#1  0xb72a6e31 in select () at ../sysdeps/unix/syscall-template.S:81
#2  0xb6aac58b in ?? () from /usr/lib/i386-linux-gnu/librabbitmq.so.1
#3  0xb6aad398 in ?? () from /usr/lib/i386-linux-gnu/librabbitmq.so.1
#4  0xb6aadc12 in amqp_simple_rpc () from /usr/lib/i386-linux-gnu/librabbitmq.so.1
#5  0xb6aae535 in amqp_simple_rpc_decoded () from /usr/lib/i386-linux-gnu/librabbitmq.so.1
#6  0xb6aaa79c in amqp_queue_declare () from /usr/lib/i386-linux-gnu/librabbitmq.so.1
#7  0xb74cca3c in declareQueue (queueName=..., this=0x9006f00) at AMQPConnection.cc:150
#8  declareConsumerQueue (this=0x9006f00) at AMQPConnection.cc:167
#9  AMQPConnection::startConsuming (this=0x8ffdfa0) at AMQPConnection.cc:571
#10 0xb74cebde in AMQPConsumer::mainThread (this=0x9006860, arg=0x8ffdf38) at AMQPConsumer.cc:92
#11 0xb74965c4 in HatoholThreadBase::threadStarter (data=0x8ffdf38) at HatoholThreadBase.cc:234
#12 0xb76f09aa in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#13 0xb766cf70 in start_thread (arg=0xb13ffb40) at pthread_create.c:312
#14 0xb72aebee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

Thread 1 (Thread 0xb62517c0 (LWP 21774)):
#0  0xb77c6424 in __kernel_vsyscall ()
#1  0xb7673135 in sem_wait@@GLIBC_2.1 () at ../nptl/sysdeps/unix/sysv/linux/i386/i686/../i486/sem_wait.S:79
#2  0xb7795b72 in mlpl::SimpleSemaphore::wait (this=0x8ffefa0) at SimpleSemaphore.cc:93
#3  0xb74961b2 in HatoholThreadBase::waitExit (this=this@entry=0xbfc1d0e8) at HatoholThreadBase.cc:133
#4  0xb75c6f59 in FaceRest::waitExit (this=this@entry=0xbfc1d0e8) at FaceRest.cc:302
#5  0xb75c6f8a in FaceRest::~FaceRest (this=0xbfc1d0e8, __in_chrg=<optimized out>) at FaceRest.cc:276
#6  0x0804a522 in mainRoutine (argc=1, argc@entry=5, argv=argv@entry=0xbfc1d234) at main.cc:249
#7  0x08049d73 in main (argc=5, argv=0xbfc1d234) at main.cc:277
```

**Comment by ashie** [comment]
ちなみに #1482 とセットで起こるようになった。

**Comment by ashie** [comment]
あ、再現するようになったのは

> 一度HAPI2.0のプラグインと接続し，その後監視サーバーからそのプラグインの情報を削除したにも関わらず，

の方で、

> 以下のようにログに30秒毎に出力され続ける。

これ手の現象は発生しない。
完全に刺さっているので、別issueにすべきか。

いったんcloseする
