### ISSUE TITLE
[hap2] Cannot run test only for TestHaplib.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1430]
haplibのテストのみ実行させようとすると失敗する。
多分、循環Importをしているから。
<pre>
[hdev3]~/hatohol/server/hap2/hatohol $ PYTHONPATH=test:.. python -m unittest -v TestHaplib
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/kyamato/hatohol/server/hap2/hatohol/test/TestHaplib.py", line 21, in <module>
    import haplib
  File "haplib.py", line 38, in <module>
    from hatohol.rabbitmqconnector import RabbitMQConnector
  File "/home/kyamato/hatohol/server/hap2/hatohol/rabbitmqconnector.py", line 23, in <module>
    import haplib
  File "/home/kyamato/hatohol/server/hap2/hatohol/haplib.py", line 38, in <module>
    from hatohol.rabbitmqconnector import RabbitMQConnector
ImportError: cannot import name RabbitMQConnector
</pre>

**Comment by kz0817** [comment]
test/run-test.shで実行した場合は（読み込み順がたまたま、循環にならないので）、OKぽい。

**Comment by kz0817** [comment]
#1464 Solves  this problem. However, it has duplicated code. So we clean up the structure.
So I keep this issue open until it's completed.

**Comment by kz0817** [comment]
Currently this problem was fixed  and merged at 0904661b069.
