### ISSUE TITLE
[HAPI2] Sometimes the self monitoring feature causes crash

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1486]
```
(gdb) where
#0  0xb71d7fef in _IO_vfprintf_internal (s=s@entry=0xb23fa830, format=<optimized out>, 
    format@entry=0xb75f7f62 "%s%s", ap=0xb23fadac "\\\177_\267Э?\262\f", 
    ap@entry=0xb23fada8 "stat\\\177_\267Э?\262\f") at vfprintf.c:1661
#1  0xb728a030 in ___vsnprintf_chk (s=s@entry=0xb23fa95c "", maxlen=<optimized out>, maxlen@entry=1024, 
    flags=flags@entry=1, slen=slen@entry=1024, format=format@entry=0xb75f7f62 "%s%s", 
    args=args@entry=0xb23fada8 "stat\\\177_\267Э?\262\f") at vsnprintf_chk.c:63
#2  0xb7764a79 in vsnprintf (__ap=0xb23fada8 "stat\\\177_\267Э?\262\f", __fmt=0xb75f7f62 "%s%s", __n=1024, 
    __s=0xb23fa95c "") at /usr/include/i386-linux-gnu/bits/stdio2.h:78
#3  mlpl::StringUtils::vsprintf (fmt=fmt@entry=0xb75f7f62 "%s%s", ap=ap@entry=0xb23fada8 "stat\\\177_\267Э?\262\f")
    at StringUtils.cc:151
#4  0xb7764b6c in mlpl::StringUtils::sprintf (fmt=fmt@entry=0xb75f7f62 "%s%s") at StringUtils.cc:137
#5  0xb751dbcd in ArmUtils::createTrigger (this=0x8a189bc, armTrigger=..., triggerInfoList=...) at ArmUtils.cc:197
#6  0xb751e760 in updateTriggersForCollectingFailure (arg=..., this=0x8a15a60) at ArmUtils.cc:120
#7  updateTriggerStatus (status=@0xb23faeb8: TRIGGER_STATUS_PROBLEM, triggerIdx=@0xb23faebc: 2, this=0x8a15a60)
    at ArmUtils.cc:73
#8  ArmUtils::updateTriggerStatus (this=0x8a189bc, triggerIdx=@0xb23faebc: 2, 
    status=@0xb23faeb8: TRIGGER_STATUS_PROBLEM) at ArmUtils.cc:252
#9  0xb75e451b in setPluginConnectStatus (type=<optimized out>, errorCode=<optimized out>, this=<optimized out>)
    at HatoholArmPluginGateHAPI2.cc:542
#10 HatoholArmPluginGateHAPI2::updateSelfMonitoringTrigger (this=0x8a191a0, hasError=true, 
    type=@0xb23fafd4: NG_PLUGIN_INTERNAL_ERROR, errorCode=@0xb23fafe0: UNAVAILABLE_HAP2)
    at HatoholArmPluginGateHAPI2.cc:1926
#11 0xb75f1e06 in HatoholArmPluginGateHAPI2::procedureHandlerPutEvents (this=0x8a191a0, parser=...)
    at HatoholArmPluginGateHAPI2.cc:1717
#12 0xb749dfce in HatoholArmPluginInterfaceHAPI2::interpretHandler (this=0x8a191a8, type=..., parser=...)
    at HatoholArmPluginInterfaceHAPI2.cc:456
#13 0xb74a03c0 in HatoholArmPluginInterfaceHAPI2::AMQPHAPI2MessageHandler::handle (this=0x8a18058, consumer=..., 
    message=...) at HatoholArmPluginInterfaceHAPI2.cc:237
#14 0xb749ba9a in AMQPConsumer::mainThread (this=0x8a19240, arg=0x8a19910) at AMQPConsumer.cc:114
#15 0xb74635c4 in HatoholThreadBase::threadStarter (data=0x8a19910) at HatoholThreadBase.cc:234
#16 0xb76bd9aa in g_thread_proxy (data=0x89ede60) at /build/buildd/glib2.0-2.40.2/./glib/gthread.c:764
#17 0xb7639f70 in start_thread (arg=0xb23fbb40) at pthread_create.c:312
#18 0xb727bbee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
```

**Comment by ashie** [comment]
Fixed in #1487
