### ISSUE TITLE
multiprocessing.Queue.get()でEINTRを受けて、テストが失敗する

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1519]
テストを連続で行っているので、以前のテストで起動した子プロセスのSIGCHLDとかか？
いずれにせよ、EINTRなら再試行するべき。

また、エラーの直接的な要因ではないと思われるが、TestHaplib.HapiProcessorでは、クラスインスタンスとして、HapiProcesssorインスタンスを１つ作成し、それを再利用している。これでは、実行されたテストによって、インスタンスの内部状態が変わり、再現性を低下させる可能性がある。テスト毎に作成するように変更する。

失敗の例。
https://travis-ci.org/project-hatohol/hatohol/jobs/75575033
<pre>
======================================================================

ERROR: test_wait_acknowledge_timeout (TestHaplib.HapiProcessor)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/project-hatohol/hatohol/server/hap2/hatohol/test/TestHaplib.py", line 553, in test_wait_acknowledge_timeout

    self.assertRaises(Queue.Empty, wait_acknowledge, 1)

  File "/usr/lib/python2.7/unittest/case.py", line 471, in assertRaises

    callableObj(*args, **kwargs)

  File "/home/travis/build/project-hatohol/hatohol/server/hap2/hatohol/haplib.py", line 582, in __wait_acknowledge

    if self.__reply_queue.get(True, self.__timeout_sec) == True:

  File "/usr/lib/python2.7/multiprocessing/queues.py", line 131, in get

    if timeout < 0 or not self._poll(timeout):

IOError: [Errno 4] Interrupted system call

======================================================================

ERROR: test_wait_response_timeout (TestHaplib.HapiProcessor)
----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/project-hatohol/hatohol/server/hap2/hatohol/test/TestHaplib.py", line 574, in test_wait_response_timeout

    self.assertRaises(Queue.Empty, wait_response, test_id)

  File "/usr/lib/python2.7/unittest/case.py", line 471, in assertRaises

    callableObj(*args, **kwargs)

  File "/home/travis/build/project-hatohol/hatohol/server/hap2/hatohol/haplib.py", line 592, in __wait_response

    pm = self.__reply_queue.get(True, self.__timeout_sec)

  File "/usr/lib/python2.7/multiprocessing/queues.py", line 131, in get

    if timeout < 0 or not self._poll(timeout):

IOError: [Errno 4] Interrupted system call

----------------------------------------------------------------------
</pre>

**Comment by kz0817** [comment]
#1521がマージされ、修正されたようなのでクローズする。
