### ISSUE TITLE
[WebUI] URLErrorで存在しないmethodを呼んでいる？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1578]
hatohol/forwardview.pyでエラーが発生した際、URLErrorに存在しないread()を呼んでいるとのログあり
<pre>
[Mon Sep 28 21:02:59.533197 2015] [:error] [pid 2740] Internal Server Error: /tunnel/login
[Mon Sep 28 21:02:59.533211 2015] [:error] [pid 2740] Traceback (most recent call last):
[Mon Sep 28 21:02:59.533215 2015] [:error] [pid 2740]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
[Mon Sep 28 21:02:59.533225 2015] [:error] [pid 2740]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Sep 28 21:02:59.533227 2015] [:error] [pid 2740]   File "/usr/libexec/hatohol/client/hatohol/forwardview.py", line 63, in jsonforward
[Mon Sep 28 21:02:59.533229 2015] [:error] [pid 2740]     response = HttpResponse(e.read(), content_type='application/json', status=e.code)
[Mon Sep 28 21:02:59.533229 2015] [:error] [pid 2740] AttributeError: 'URLError' object has no attribute 'read'
</pre>

たしかにソースをみると次のようになっている
<pre>
    except urllib2.URLError, e:
        response = HttpResponse(e.read(), content_type='application/json', status=e.code)
</pre>

書きによると、たしかにread()はない。reasonを使うべきか。
http://docs.python.jp/2/library/urllib2.html#urllib2.URLError

**Comment by kz0817** [comment]
また、URLError.codeも存在しないので、これもエラーを生じる。

**Comment by kz0817** [comment]
#1579がマージされたのでクローズ。
