### ISSUE TITLE
イベント画面の設定で保存を押すと次のエラーになる

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1751]
master:aa854f7acc366e61を試験運用していたところ、イベント画面の設定で、表示項目をカスタマイズして保存すると以下のエラーがでました。原因などわかるでしょうか？

Chrome  46.0.2490.86のConsole log
<pre>
POST http://hdev3run:8000/event-filters/ 500 (INTERNAL SERVER ERROR)send @ jquery.js:8526jQuery.extend.ajax @ jquery.js:7978request @ hatohol_connector.js:183HatoholConnector.start @ hatohol_connector.js:88HatoholConnector @ hatohol_connector.js:72(anonymous function) @ hatohol_events_view_config.js:286jQuery.extend.map @ jquery.js:773saveFilters @ hatohol_events_view_config.js:279HatoholEventsViewConfig.saveAll @ hatohol_events_view_config.js:237(anonymous function) @ hatohol_events_view_config.js:123jQuery.event.dispatch @ jquery.js:3074elemData.handle @ jquery.js:2750
</pre>

manage.pyのログ
<pre>
[19/Nov/2015 18:49:04] "GET /tunnel/summary?beginTime=1445302144 HTTP/1.1" 200 229
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:202: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if not self.blank and value in validators.EMPTY_VALUES:

/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:159: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in validators.EMPTY_VALUES:

Internal Server Error: /event-filters/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/kyamato/hatohol/client/hatohol/views.py", line 204, in event_filters
    'hatohol.views.evnet_filters')
  File "/home/kyamato/hatohol/client/hatohol/views.py", line 142, in json_settings_handler
    model.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Incorrect string value: '\xE5\x85\xA8\xE3\x81\xA6...' for column 'settings_json' at row 1
[19/Nov/2015 18:49:37] "POST /event-filters/ HTTP/1.1" 500 11130
[19/Nov/2015 18:49:37] "POST /userconfig HTTP/1.1" 200 0
</pre>
![event-dialog](https://cloud.githubusercontent.com/assets/2610513/11289253/40ce43be-8f6e-11e5-8ec9-b52ec1900e2f.png)

**Comment by ashie** [comment]
DjangoでDBの文字コードとしてUTF-8を想定しているようなので、クライアントのDBの
作成手順を以下のように変更しています。

client/README.md:
```
mysql> CREATE DATABASE hatohol_client DEFAULT CHARACTER SET utf8;
```

**Comment by kz0817** [comment]
ありがとうございました。エラーでなくなりました。

Djangoのほうで以下の警告が以前として出るのですが、これは問題ないでしょうか？
<pre>
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:202: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if not self.blank and value in validators.EMPTY_VALUES:

/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:159: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in validators.EMPTY_VALUES:
</pre>

**Comment by ashie** [comment]
あ、気づいてなかったです。
調べます。

**Comment by ashie** [comment]
```
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:159: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in validators.EMPTY_VALUES:
```

初期状態で保存したときの上記のvalue、self.empty_stringはそれぞれ以下

value (型はbytestring): 
```
`{"name":"\u5168\u3066\uff0831\u65e5\u9593\uff09","days":31,"incident":{"enable":false,"selected":[]},"type":{"enable":false,"selected":[]},"severity":{"enable":false,"selected":[]},"server":{"enable":false,"exclude":false,"selected":[]},"hostgroup":{"enable":false,"exclude":false,"selected":[]},"host":{"enable":false,"exclude":false,"selected":[]}}'
```
self.empty_string: 
```
[None, u'', [], (), {   }]
```

bytestringなvalueと、self.empty_string内のu''を比較しようとして上記警告が出ている。
valueがbytestringで渡ってきているのでは、viewの方でリクエストのbodyを直接渡しているから。
実害は無いものの、当然修正した方が良い。

 django.utils.encodingのsmart_textで変換してやれば良い。
