### ISSUE TITLE
TestStandardHap.TestStandardHapがローカルで失敗する

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2222]
最近入ったConfigFileParserが関係している可能性がある。
TravisCIでなぜ通るのか？
<pre>
$  PYTHONPATH=test:.. python -m unittest -v TestStandardHap.TestStandardHap
test_normal_run (TestStandardHap.TestStandardHap) ... 2016-03-31 13:20:05,754     INFO [ 3212] hatohol.standardhap:runpy.pyc:62:  Configuration file: /home/kyamato/m4/etc/hatohol/hap2.conf
2016-03-31 13:20:05,755     INFO [ 3212] hatohol.transporter:runpy.pyc:170:  Registered: RabbitMQHapiConnector
2016-03-31 13:20:05,755     INFO [ 3212] hatohol.transporter:runpy.pyc:163:  Loaded transporter module: /usr/lib/python2.7/dist-packages/hatohol/transporters
2016-03-31 13:20:05,755     INFO [ 3212] hatohol.transporter:runpy.pyc:170:  Registered: RabbitMQHapiConnector
2016-03-31 13:20:05,755     INFO [ 3212] hatohol.transporter:runpy.pyc:163:  Loaded transporter module: /home/kyamato/hatohol/server/hap2/hatohol/transporters
usage: python -m unittest [-h] [--config CONFIG]
                          [--log {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
                          [--log-conf LOG_CONF_FILE] [-p]
                          [--polling-targets [{hosts,host_groups,host_group_membership,triggers,events} [{hosts,host_groups,host_group_membership,triggers,events} ...]]]
                          [--status-log-interval STATUS_LOG_INTERVAL]
                          [--transporter TRANSPORTER]
                          [--amqp-broker AMQP_BROKER] [--amqp-port AMQP_PORT]
                          [--amqp-vhost AMQP_VHOST] [--amqp-queue AMQP_QUEUE]
                          [--amqp-user AMQP_USER]
                          [--amqp-password AMQP_PASSWORD]
                          [--amqp-ssl-key AMQP_SSL_KEY]
                          [--amqp-ssl-cert AMQP_SSL_CERT]
                          [--amqp-ssl-ca AMQP_SSL_CA]
python -m unittest: error: unrecognized arguments: -v TestStandardHap.TestStandardHap
ERROR

======================================================================
ERROR: test_normal_run (TestStandardHap.TestStandardHap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestStandardHap.py", line 98, in test_normal_run
    hap()
  File "/home/kyamato/hatohol/server/hap2/hatohol/standardhap.py", line 138, in __call__
    args = self.__setup()
  File "/home/kyamato/hatohol/server/hap2/hatohol/standardhap.py", line 128, in __setup
    args = self.__parser.parse_args()
  File "/usr/lib/python2.7/dist-packages/hatohol/hap.py", line 180, in parse_args
    return self.parser.parse_args(self.remaining_args)
  File "/usr/lib/python2.7/argparse.py", line 1693, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python2.7/argparse.py", line 2363, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/usr/lib/python2.7/argparse.py", line 2351, in exit
    _sys.exit(status)
SystemExit: 2

----------------------------------------------------------------------
Ran 1 test in 0.005s
</pre>

**Comment by kz0817** [comment]
修正がマージされたのでクローズします。
