### ISSUE TITLE
[server] Crash on idling a connection

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#98]
For the last few days, sometimes (one or two times per day) Hatohol server crashes while polling on my environment.
It seems that idle-timer of SoupSeesion triggers it.

* https://github.com/project-hatohol/hatohol/blob/master/server/src/ArmZabbixAPI.cc#L302

The idle-timer is queued from ArmZabbixAPI thread, but run on main thread.

* https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--idle-timeout
* https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--async-context
* https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--use-thread-context

Backtrace:
<pre>
Thread 9 (Thread 0xb4dfeb40 (LWP 11934)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb7663da8 in sem_timedwait () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xb754564d in ArmBase::sleepInterruptible (this=0x91477ec, sleepTime=60) at ArmBase.cc:174
#3  0xb7545b85 in setUpdateType (type=ArmBase::UPDATE_POLLING, this=0x916d270) at ArmBase.cc:106
#4  ArmBase::mainThread (this=0x91477ec, arg=0x917e9c8) at ArmBase.cc:220
#5  0xb7554147 in ArmZabbixAPI::mainThread (this=0x91477ec, arg=0x917e9c8) at ArmZabbixAPI.cc:1005
#6  0xb75adc90 in HatoholThreadBase::threadStarter (data=0x917e9c8) at HatoholThreadBase.cc:204
#7  0xb76e0fc3 in g_thread_proxy (data=0x90f7460) at /build/buildd/glib2.0-2.36.0/./glib/gthread.c:798
#8  0xb765dd78 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#9  0xb7331fee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 8 (Thread 0xb5fffb40 (LWP 11932)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb73229db in poll () from /lib/i386-linux-gnu/libc.so.6
#2  0xb76ca2db in poll (__timeout=-1, __nfds=2, __fds=0xb5608290) at /usr/include/i386-linux-gnu/bits/poll2.h:46
#3  g_poll (fds=0xb5608290, nfds=2, timeout=-1) at /build/buildd/glib2.0-2.36.0/./glib/gpoll.c:132
#4  0xb76bb6d0 in g_main_context_poll (n_fds=2, fds=0xb5608290, timeout=<optimized out>, context=0x9111188, priority=<optimized out>) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3995
#5  g_main_context_iterate (context=context@entry=0x9111188, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3696
#6  0xb76bb831 in g_main_context_iteration (context=0x9111188, may_block=1) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3762
#7  0xb75978f6 in FaceRest::mainThread (this=0xbf846e10, arg=0x910eb78) at FaceRest.cc:536
#8  0xb75adc90 in HatoholThreadBase::threadStarter (data=0x910eb78) at HatoholThreadBase.cc:204
#9  0xb76e0fc3 in g_thread_proxy (data=0x90f7400) at /build/buildd/glib2.0-2.36.0/./glib/gthread.c:798
#10 0xb765dd78 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#11 0xb7331fee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 7 (Thread 0xb55ffb40 (LWP 11933)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb73229db in poll () from /lib/i386-linux-gnu/libc.so.6
#2  0xb76ca2db in poll (__timeout=__timeout@entry=60000, __nfds=2, __nfds@entry=3077565782, __fds=__fds@entry=0xb55feae0) at /usr/include/i386-linux-gnu/bits/poll2.h:46
#3  g_poll (fds=fds@entry=0xb55feae0, nfds=nfds@entry=2, timeout=timeout@entry=60000) at /build/buildd/glib2.0-2.36.0/./glib/gpoll.c:132
#4  0xb70423a0 in g_socket_condition_timed_wait (socket=socket@entry=0xb5607510, condition=condition@entry=G_IO_IN, timeout=60000, cancellable=cancellable@entry=0xb4400f80, error=error@entry=0xb55fec8c) at /build/buildd/glib2.0-2.36.0/./gio/gsocket.c:3562
#5  0xb70425c8 in g_socket_condition_wait (socket=0xb5607510, condition=G_IO_IN, cancellable=0xb4400f80, error=0xb55fec8c) at /build/buildd/glib2.0-2.36.0/./gio/gsocket.c:3427
#6  0xb7042910 in g_socket_receive_with_blocking (socket=0xb5607510, buffer=buffer@entry=0xb448ed00 "\370\062N\264\340\237L\264", size=size@entry=8192, blocking=blocking@entry=1, cancellable=cancellable@entry=0xb4400f80, error=error@entry=0xb55fec8c) at /build/buildd/glib2.0-2.36.0/./gio/gsocket.c:2485
#7  0xb704a4f8 in g_socket_input_stream_read (stream=0x9192db0, buffer=0xb448ed00, count=8192, cancellable=0xb4400f80, error=0xb55fec8c) at /build/buildd/glib2.0-2.36.0/./gio/gsocketinputstream.c:127
#8  0xb7027e50 in g_input_stream_read (stream=0x9192db0, buffer=0xb448ed00, count=8192, cancellable=0xb4400f80, error=0xb55fec8c) at /build/buildd/glib2.0-2.36.0/./gio/ginputstream.c:204
#9  0xb7037e6d in g_pollable_stream_read (stream=0x9192db0, buffer=buffer@entry=0xb448ed00, count=count@entry=8192, blocking=blocking@entry=1, cancellable=cancellable@entry=0xb4400f80, error=error@entry=0xb55fec8c) at /build/buildd/glib2.0-2.36.0/./gio/gpollableutils.c:219
#10 0xb719747a in soup_filter_input_stream_read_until (fstream=fstream@entry=0xb4403090, buffer=buffer@entry=0xb4429a40, length=length@entry=8192, boundary=boundary@entry=0xb71c3604, boundary_length=boundary_length@entry=1, blocking=blocking@entry=1, include_boundary=include_boundary@entry=1, got_boundary=got_boundary@entry=0xb55fed48, cancellable=cancellable@entry=0xb4400f80, error=error@entry=0xb55fedcc) at soup-filter-input-stream.c:220
#11 0xb7197615 in soup_filter_input_stream_read_line (fstream=0xb4403090, buffer=0xb4429a40, length=length@entry=8192, blocking=1, got_line=got_line@entry=0xb55fed48, cancellable=cancellable@entry=0xb4400f80, error=error@entry=0xb55fedcc) at soup-filter-input-stream.c:181
#12 0xb71a1d22 in read_headers (error=0xb55fedcc, cancellable=0xb4400f80, msg=0xb44048f0) at soup-message-io.c:180
#13 io_read (msg=msg@entry=0xb44048f0, cancellable=cancellable@entry=0xb4400f80, error=error@entry=0xb55fedcc) at soup-message-io.c:485
#14 0xb71a2473 in io_run_until (msg=msg@entry=0xb44048f0, read_state=read_state@entry=SOUP_MESSAGE_IO_STATE_DONE, write_state=write_state@entry=SOUP_MESSAGE_IO_STATE_DONE, cancellable=0xb4400f80, error=error@entry=0xb55fee08) at soup-message-io.c:828
#15 0xb71a2e6c in io_run (msg=0xb44048f0, user_data=0x0) at soup-message-io.c:891
#16 0xb71a31d0 in soup_message_io_client (item=0xb44048f0, item@entry=0xb4407b70, iostream=0x0, async_context=async_context@entry=0x0, get_headers_cb=get_headers_cb@entry=0xb719f410 <get_request_headers>, parse_headers_cb=parse_headers_cb@entry=0xb719f230 <parse_response_headers>, header_data=header_data@entry=0xb4407b70, completion_cb=completion_cb@entry=0x0, completion_data=completion_data@entry=0xb4407b70) at soup-message-io.c:1064
#17 0xb719f804 in soup_message_send_request (item=item@entry=0xb4407b70, completion_cb=completion_cb@entry=0x0, user_data=user_data@entry=0xb4407b70) at soup-message-client-io.c:153
#18 0xb718e066 in soup_connection_send_request (conn=0xb44751c8, item=item@entry=0xb4407b70, completion_cb=completion_cb@entry=0x0, user_data=user_data@entry=0xb4407b70) at soup-connection.c:979
#19 0xb71ae753 in soup_session_send_queue_item (session=0xb4406000, item=item@entry=0xb4407b70, completion_cb=completion_cb@entry=0x0) at soup-session.c:1084
#20 0xb71b36a6 in process_queue_item (item=item@entry=0xb4407b70) at soup-session-sync.c:257
#21 0xb71b3b15 in soup_session_sync_send_message (session=0xb4406000, msg=0xb44048f0) at soup-session-sync.c:335
#22 0xb71aee9c in soup_session_send_message (session=0xb4406000, msg=0xb44048f0) at soup-session.c:1500
#23 0xb754ba5a in ArmZabbixAPI::queryCommon (this=0x9146e54, agent=...) at ArmZabbixAPI.cc:367
#24 0xb754be98 in _M_dispose (__a=..., this=0xb44d31e8) at /usr/include/c++/4.7/bits/basic_string.h:237
#25 ~basic_string (this=0xb55ff058, __in_chrg=<optimized out>) at /usr/include/c++/4.7/bits/basic_string.h:536
#26 ArmZabbixAPI::queryTrigger (this=0x9146e54, requestSince=1387284564) at ArmZabbixAPI.cc:402
#27 0xb7555f26 in ~ItemPtr (this=0xb55ff158, __in_chrg=<optimized out>) at ItemPtr.h:49
#28 ArmZabbixAPI::updateItems (this=0x0) at ArmZabbixAPI.cc:937
#29 0x0804c0ec in std::string::_Rep::_S_empty_rep_storage ()
#30 0x00000000 in ?? ()

Thread 6 (Thread 0xb33fdb40 (LWP 11937)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb7663bf5 in sem_wait@@GLIBC_2.1 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xb75a6129 in _M_pop_front_aux (this=0x9111268) at /usr/include/c++/4.7/bits/deque.tcc:522
#3  pop_front (this=0x9111268) at /usr/include/c++/4.7/bits/stl_deque.h:1411
#4  pop (this=0x9111268) at /usr/include/c++/4.7/bits/stl_queue.h:240
#5  popJob (this=0x9111238) at FaceRest.cc:212
#6  waitNextJob (this=<optimized out>) at FaceRest.cc:310
#7  FaceRest::Worker::mainThread (this=0xb5607a98, arg=0xb5607b20) at FaceRest.cc:298
#8  0xb75adc90 in HatoholThreadBase::threadStarter (data=0xb5607b20) at HatoholThreadBase.cc:204
#9  0xb76e0fc3 in g_thread_proxy (data=0xb5603fb0) at /build/buildd/glib2.0-2.36.0/./glib/gthread.c:798
#10 0xb765dd78 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#11 0xb7331fee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 5 (Thread 0xb43ffb40 (LWP 11935)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb7663bf5 in sem_wait@@GLIBC_2.1 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xb75a6129 in _M_pop_front_aux (this=0x9111268) at /usr/include/c++/4.7/bits/deque.tcc:522
#3  pop_front (this=0x9111268) at /usr/include/c++/4.7/bits/stl_deque.h:1411
#4  pop (this=0x9111268) at /usr/include/c++/4.7/bits/stl_queue.h:240
#5  popJob (this=0x9111238) at FaceRest.cc:212
#6  waitNextJob (this=<optimized out>) at FaceRest.cc:310
#7  FaceRest::Worker::mainThread (this=0xb5606778, arg=0xb5607820) at FaceRest.cc:298
#8  0xb75adc90 in HatoholThreadBase::threadStarter (data=0xb5607820) at HatoholThreadBase.cc:204
#9  0xb76e0fc3 in g_thread_proxy (data=0xb5603f50) at /build/buildd/glib2.0-2.36.0/./glib/gthread.c:798
#10 0xb765dd78 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#11 0xb7331fee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 4 (Thread 0xb2bfcb40 (LWP 11938)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb7663bf5 in sem_wait@@GLIBC_2.1 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xb75a6129 in _M_pop_front_aux (this=0x9111268) at /usr/include/c++/4.7/bits/deque.tcc:522
#3  pop_front (this=0x9111268) at /usr/include/c++/4.7/bits/stl_deque.h:1411
#4  pop (this=0x9111268) at /usr/include/c++/4.7/bits/stl_queue.h:240
#5  popJob (this=0x9111238) at FaceRest.cc:212
#6  waitNextJob (this=<optimized out>) at FaceRest.cc:310
#7  FaceRest::Worker::mainThread (this=0xb5607c30, arg=0xb5607cb8) at FaceRest.cc:298
#8  0xb75adc90 in HatoholThreadBase::threadStarter (data=0xb5607cb8) at HatoholThreadBase.cc:204
#9  0xb76e0fc3 in g_thread_proxy (data=0xb5604000) at /build/buildd/glib2.0-2.36.0/./glib/gthread.c:798
#10 0xb765dd78 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#11 0xb7331fee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 3 (Thread 0xb3bfeb40 (LWP 11936)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb7663bf5 in sem_wait@@GLIBC_2.1 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xb75a6129 in _M_pop_front_aux (this=0x9111268) at /usr/include/c++/4.7/bits/deque.tcc:522
#3  pop_front (this=0x9111268) at /usr/include/c++/4.7/bits/stl_deque.h:1411
#4  pop (this=0x9111268) at /usr/include/c++/4.7/bits/stl_queue.h:240
#5  popJob (this=0x9111238) at FaceRest.cc:212
#6  waitNextJob (this=<optimized out>) at FaceRest.cc:310
#7  FaceRest::Worker::mainThread (this=0xb5607900, arg=0xb5607988) at FaceRest.cc:298
#8  0xb75adc90 in HatoholThreadBase::threadStarter (data=0xb5607988) at HatoholThreadBase.cc:204
#9  0xb76e0fc3 in g_thread_proxy (data=0xb5603f80) at /build/buildd/glib2.0-2.36.0/./glib/gthread.c:798
#10 0xb765dd78 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#11 0xb7331fee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 2 (Thread 0xb6927b40 (LWP 11930)):
#0  0xb77a1424 in __kernel_vsyscall ()
#1  0xb73229db in poll () from /lib/i386-linux-gnu/libc.so.6
#2  0xb76ca2db in poll (__timeout=-1, __nfds=3, __fds=0xb60023c8) at /usr/include/i386-linux-gnu/bits/poll2.h:46
#3  g_poll (fds=0xb60023c8, nfds=3, timeout=-1) at /build/buildd/glib2.0-2.36.0/./glib/gpoll.c:132
#4  0xb76bb6d0 in g_main_context_poll (n_fds=3, fds=0xb60023c8, timeout=<optimized out>, context=0x90f6518, priority=<optimized out>) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3995
#5  g_main_context_iterate (context=0x90f6518, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3696
#6  0xb76bbc2b in g_main_loop_run (loop=0x90f64e0) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3895
#7  0xb70aabca in gdbus_shared_thread_func (user_data=0x90f6500) at /build/buildd/glib2.0-2.36.0/./gio/gdbusprivate.c:278
#8  0xb76e0fc3 in g_thread_proxy (data=0x90f3180) at /build/buildd/glib2.0-2.36.0/./glib/gthread.c:798
#9  0xb765dd78 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#10 0xb7331fee in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 1 (Thread 0xb6991780 (LWP 11929)):
#0  soup_connection_set_state (conn=conn@entry=0xb4408960, state=state@entry=SOUP_CONNECTION_DISCONNECTED) at soup-connection.c:898
#1  0xb718d1ed in soup_connection_disconnect (conn=conn@entry=0xb4408960) at soup-connection.c:814
#2  0xb718d28b in idle_timeout (conn=conn@entry=0xb4408960) at soup-connection.c:350
#3  0xb76bc107 in g_timeout_dispatch (source=source@entry=0xb44178d0, callback=0xb718d270 <idle_timeout>, user_data=0xb4408960) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:4413
#4  0xb76bb3b3 in g_main_dispatch (context=0x90ef9d8, context@entry=0x90f4330) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3054
#5  g_main_context_dispatch (context=context@entry=0x90ef9d8) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3630
#6  0xb76bb750 in g_main_context_iterate (context=0x90ef9d8, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3701
#7  0xb76bbc2b in g_main_loop_run (loop=0x9148940) at /build/buildd/glib2.0-2.36.0/./glib/gmain.c:3895
#8  0x080498e6 in mainRoutine (argc=2, argv=0xb75e2e90 <UnifiedDataStore::deleteAccessInfo(int, OperationPrivilege const&)+32>) at main.cc:196
#9  0x08049334 in main (argc=2, argv=0xbf846f34) at main.cc:205
</pre>

**Comment by ashie** [comment]
idle-timeoutをセットしなければ問題は発生しない。
また、idle-timeoutをセットしていなくても、通信が刺さったままになるような問題は
今のところ発生していないので、いったんクローズする。
